sudo: false
language: java
jdk:
  - oraclejdk8

env:
  - TERM=dumb

install:
  - ./bundles/gradlew --version

script:
  - ./bundles/gradlew --continue

after_success:
  - git status

cache:
  directories:
    - cnf/cache/stable