sudo: false
language: 
  - java
  - node_js
  
node_js:
  - "7" 
 
jdk:
  - oraclejdk8

env:
  - TERM=dumb

install:
  - cd web && npm run init
  - cd ../bundles && ./gradlew --version

script:
  - echo $DUMMY
#  - cd ../web && npm run build-prod
#  - cd ../bundles && ./gradlew build --continue
#  - cd ../bundles && ./gradlew export
#  - cd ..

after_success:
  - git status

cache:
  directories:
    - cnf/cache/stable

deploy:
  provider: releases
  api_key: GITHUB_OAUTH
  file: /bundles/specmate-std-env/generated/distributions/executable/specmate.jar
  skip_cleanup: true
  on:
    branch: develop
