sudo: false
language: 
  - java
  - node_js
  
node_js:
  - "7" 
 
jdk:
  - oraclejdk8

env:
  - TERM=dumb

install:
  - cd web && npm run init
  - cd ../bundles && ./gradlew --version

script:
  - cd ../web && npm run build-prod
  - cd ../bundles && ./gradlew build --continue
  - cd ../bundles && ./gradlew export
  - cd ..

after_success:
  - git status

cache:
  directories:
    - cnf/cache/stable

deploy:
  provider: releases
  api_key: Rywi+Se0PoynPy4dscCYngypauzkAQ6r194AtKLoIddJsVAG70MSSJG0XLNnPjN4225x9P64LgR5hlvM6zzlLlOxVmhJcSnV2ZW/c2ykNDEI03oUT9MoIfY46MFRTeEBK0oocxOblNnz0ncgteP9w7hcz0UEo3UIUXSijaxomipalwR2Re5CYk+BY+NZ6bXRJKmBnndPz/XVOcSMxjO5pGoym/kZzdwFcGsU7GCrel8iTXgOJziIoh+sBhqaMte5dbRnSAgDVchq0vzRvH8Ty5IcLTlyCkqEaQEjn2p1+yc+tFV3zfWpcVyMYhzKzya03+d4Dp0dxr8OONWSWoxKx37RaX47tH7uG/e2yT7FpuXfKhr/syJG06GM2IF6x+skiJWAW6R8zOCHATBWss2gHRms9V+7aXuE5zCBl9vRrvdW7YXeF0Dp7Lda235I7++3pzQCymFMCb4Se3BHVdDKhYAikbHw/KDhSAWVUd+s7tfsNG5mEgxjZgtEhK1EzQRjvCbSZFtXyVWjvb0LMYKC7/yR4hEadfnGBifGEJkdZsSw3JnpOBSDKVHMPPGb+SuPGc8Su9CuD1ssDyyvoWKkSYQmg097Zp1ztdHNt2MtiyucNWJaor8WlSZ03MsBzZkc+eQt4vT+mTxfe5DSOQmNk9rUvP1F2jmdhvtQZDzDhoo=

by zonca
  file: /bundles/specmate-std-env/generated/distributions/executable/specmate.jar
  skip_cleanup: true
  on:
    branch: develop
