sudo: false
language: 
  - java
  - node_js
  
node_js:
  - "7" 
 
jdk:
  - oraclejdk8

env:
  - TERM=dumb
  - FILE=/bundles/specmate-std-env/generated/distributions/executable/specmate.jar

install:
  - cd web && npm run init
  - cd ../bundles && ./gradlew --version

jobs:
  include:
    - stage: UI build
      script: cd ../web && npm run build-prod
    - stage: Backend build
      script: cd ../bundles && ./gradlew build --continue && ./gradlew check && ./gradlew export && cd ..
    - stage: Deploy
      script: "curl -H \"Authorization: token $GITHUB_OAUTH\" -H \"Content-Type: $(file -b --mime-type $FILE)\" --data-binary @$FILE \"https://uploads.github.com/repos/hubot/singularity/releases/123/assets?name=$(basename $FILE)\""

after_success:
  - git status

cache:
  directories:
    - cnf/cache/stable

#deploy:
#  provider: releases
#  api_key: ${GITHUB_OAUTH}
#  file: /bundles/specmate-std-env/generated/distributions/executable/specmate.jar
#  skip_cleanup: true
#  on:
#    branch: develop
