sudo: false
language: 
  - java
  - node_js
  
node_js:
  - "7" 
 
jdk:
  - oraclejdk8

env:
  - TERM=dumb

install:
  - cd web && npm run init
  - cd ../bundles && ./gradlew --version

script:
  - cd ../web && npm run build-prod
  - cd ../bundles && ./gradlew build --continue
  - cd ../bundles && ./gradlew export
  - cd ..

after_success:
  - git status

cache:
  directories:
    - cnf/cache/stable

deploy:
  provider: releases
  api_key: 1+vzMQXmuoUBoJEFmnii8l8mwjgtOyVHLjuWibapEg+jfFwuBRDqk3vHn7l4Oxz8993KiCpJ5WJcBnBG67GeBct7IO8aYeSNjTDogGswO3PQCIS53HftoXsmNnCk6Mh9bLaj1eWNgi1bIj0WKxDeIb0BGQ6Kd4YPIabylb3HmL7cbIQ1aq/SHs3wOID5dATAyVFPrTfnZDp0J9e5oCowEGjo+NXQaRaqlETvDSsaEY+MEwoMt/Z4Oy0DqTReVcVgHYkfChmsm6KB0QOJ+c1Bk6YQXK4cAKR5MAn3feeLLdPBFepEzp5lA4m6matI1bqNBjlG229X+PtwPJXyghZ5EF8bgG54sh0n+fSrwfv0ZHB5gLnhnhcJU34HGaBZAkOzpmwvjQGIX0GlTQ3DSjEXf59sC7TMd6aws9I9Nzig4zn71X2cd5msp8Lqu++lFHkfn8/diQtEAlU9d+hWhkhIq1uVKTBNa9bSLD1M1VrBlf5dFBgfh6pYmJlZI4PXCmvltur16oRn2ItDdTcmcfwtc9DRDZGf5eaWki1J5vLD1Cab/C0T5LbhXv0vfHHJ1DbjUQQd367lgEjUhtVrBH+zqhVntAY3fmiOgHaS+RmDhmImO/Hcd3UmhdnrW18GqLJcReQM3cWBTbAXPQsZj1lqk9oGzoVNHsjTEOJZsfONJ6w=
  file: /bundles/specmate-std-env/generated/distributions/executable/specmate.jar
  skip_cleanup: true
  on:
    branch: develop
